[package]
name = "extensions"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
url.workspace = true
wasmi = { version = "=2.0.0", default-features = false, features = ["std", "validate", "stable", "portable-dispatch"] }

[dev-dependencies]
nivra-extension-sdk = { path = "../../examples/extensions/sdk" }
wat = "=1.245.1"

[lints]
workspace = true
